src/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    path('git_hub/',views.repo, name='git_hub'), 
    path('find_people/',views.find_people, name='find_people'),
    path('payment/',views.payment, name='payment'),
    path('chat_with_friend/',views.chat_with_friend, name='chat_with_friend'),
    path('gallary/',views.gallary, name='gallary') 
 
    
]

src/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('like', views.like, name='like'),
    path('scookie',views.setcookie),  
    path('gcookie',views.getcookie),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} Published by
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Yorumlar</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
       Be the first to comment!
      </div>
      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Add</button>
            </form>
          </div>
        </div>
        </div>
        
      </div>

      

{% endblock body %}