src/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    path('git_hub/',views.repo, name='git_hub'), 
    path('find_people/',views.find_people, name='find_people'),
    path('payment/',views.payment, name='payment'),
    path('chat_with_friend/',views.chat_with_friend, name='chat_with_friend'),
    path('gallary/',views.gallary, name='gallary') 
 
    
]

src/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('like', views.like, name='like'),
    path('scookie',views.setcookie),  
    path('gcookie',views.getcookie),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),

]

src/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author")
    title = models.CharField(max_length = 50,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Creation Date")
    article_image = models.FileField(blank = True,null = True,verbose_name="Add Photo to Article")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']


class Like(models.Model):
    likes = models.ForeignKey(Article, on_delete = 'CASCADE')


class Repository(models.Model):
    repo_name =  models.CharField(max_length = 50)
    repo_url =  models.CharField(max_length = 100)
    repo_dec =  models.TextField(max_length = 200)

src/article/forms.py
from django import forms
from .models import Article, Repository

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]



class GithubForm(forms.ModelForm):
    class Meta:
        model = Repository
        fields = ["repo_name","repo_url","repo_dec"]        

src/article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm, GithubForm
from .models import Article, Comment, Like, Repository
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import json
from django.core import serializers
from django.contrib.auth.models import User

# Create your views here.



def setcookie(request):  
    response = HttpResponse("Cookie Set")  
    response.set_cookie('java-tutorial', 'javatpoint.com')  
    response.set_cookie('java-kjk', 'fdbjhks SHUKLA')  
    return response  


def getcookie(request):  
    tutorial  = request.COOKIES 
    print(tutorial['csrftoken'])
    return HttpResponse("java tutorials @: ",tutorial['csrftoken']);




def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"blogs.html",{"articles":articles})


@login_required(login_url = "user:login")
def payment(request):
    return render(request,'payment.html'); 



@login_required(login_url = "user:login")
def chat_with_friend(request):
    return render(request,'chat_with_friend.html');   


@login_required(login_url = "user:login")
def gallary(request):
    return render(request,'gallary.html');         



def index(request): 
    repo_list = Repository.objects.all()
    # keyword = request.GET.get("keyword")
    # if keyword:
    #     articles = Article.objects.filter(title__contains = keyword)
    #     return render(request,"articles.html",{"articles":articles})
    # articles = Article.objects.all()
    # get_likes = Like.objects.all().count()
    return render(request,"index.html",{"repo_list":repo_list})


def like(request):
    if request.method == 'GET':
        post_id = request.GET['like_id']
        print(post_id)
        user = Article.objects.get(id=post_id)
        likedpost = Article.objects.get(id=post_id)
        print(likedpost)
        m = Like( likes = likedpost )
        m.save()
        get_likes = Like.objects.all()
        data = serializers.serialize('json', list(get_likes))
        return HttpResponse(data, content_type="application/json")
    else:
        return HttpResponse("unsuccesful")    


    
    
def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def find_people(request):
    users = User.objects.all()
    return render(request,"find_people.html",{"users_list":users})    


@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {"articles":articles}
    return render(request,"blog_settings.html",context)



@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article successfully created")
        return redirect("article:articles")
    return render(request,"addarticle.html",{"form":form})


def detail(request,id): 
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article successfully updated")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})


@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Article Successfully Deleted")
    return redirect("article:dashboard")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))



@login_required(login_url = "user:login")   
def repo(request):
    if request.method == "POST":
        repo_name = request.POST.get("repo_name")
        repo_url = request.POST.get("repo_url")
        repo_dec = request.POST.get("repo_dec")
        repo_url = repo_url.strip()
        repo = Repository(repo_name = repo_name, repo_url =repo_url , repo_dec = repo_dec)
        repo.save()
        return redirect('/')

    
    return render(request,'git_hub.html')

   




  



    

src/article/templates/about.html
{% extends "layout.html" %}

{% load static %}
{% block body %}

<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <div id="about-us" class="clear">
      <!-- ####################################################################################################### -->
      <section id="about-intro" class="clear">
      	<h2>MEET OUR TEAM</h2>
        <p>We are all very different. We were born in different cities, at different times, we love different music, food, movies. But we have something that unites us all. It is our company. We are its heart. We are not just a team, we are a family.</p>
      </section>
      <!-- ####################################################################################################### -->
      <section id="team">
        <ul class="clear">
          <li class="one_quarter first">
            <figure><img src="{% static 'images/demo/team-member.gif' %}"  alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
               
              </figcaption>
            </figure>
           
          </li>
          <li class="one_quarter">
            <figure><img  src="{% static 'images/demo/team-member.gif' %}" alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
               
              </figcaption>
            </figure>
           
          </li>
          <li class="one_quarter">
            <figure><img  src="{% static 'images/demo/team-member.gif' %}"  alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
               
              </figcaption>
            </figure>
           
          </li>
          <li class="one_quarter">
            <figure><img  src="{% static 'images/demo/team-member.gif' %}"  alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
               
              </figcaption>
            </figure>
         
          </li>
          <li class="one_quarter first">
            <figure><img  src="{% static 'images/demo/team-member.gif' %}"  alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
               
              </figcaption>
            </figure>
          
          </li>
          <li class="one_quarter">
            <figure><img src="{% static 'images/demo/team-member.gif' %}" alt="">
              <figcaption>
                <p class="team_name">Name Goes Here</p>
                <p class="team_title">Job Title Here</p>
              
              </figcaption>
            </figure>
          
          </li>
          <li class="one_half">
            <div id="skillset">
              <h2>Vivamuslibero Auguer</h2>
             
             <p class="team_title">Job Title Here</p>
            </div>
          </li>
        </ul>
      </section>
      <!-- ####################################################################################################### -->
    </div>
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
  </div>
</div>
{% endblock body %}

src/article/templates/addarticle.html
{% extends "base.html" %}

{% block main %}
{% load crispy_forms_tags %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
   <div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Blogs</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add Article</button>
        </form>
    </div>
  </div> 
</main>



{% endblock main %}

src/article/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>

  <body>
  {% if request.user.is_authenticated %}
  	<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
     	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'article:articles'  %}">Blog Book</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link"  href="{% url 'user:logout'  %}" >Sign out</a>
        </li>
      </ul>
    </nav>

  {% else %}
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'article:articles'  %}">Blog Book</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link"  href="{% url 'user:login'  %}">Sign In</a>
        </li>
      </ul>
   </nav>

  {% endif %}
  {% if request.user.is_authenticated %}
  <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'index'  %}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link"  href="{% url 'article:dashboard'  %}">
                  <span data-feather="file"></span>
                  Blog Settings
                </a>
              </li>
               <li class="nav-item">
                <a class="nav-link"  href="{% url 'article:find_people'  %}">
                  <span data-feather="users"></span>
                 Find People
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'article:chat_with_friend'  %}">
                  <span data-feather="shopping-cart"></span>
                    Chat With Friend
                </a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link" href="{% url 'article:gallary'  %}">
                  <span data-feather="bar-chart-2"></span>
                  Gallary
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'article:payment'  %}">
                  <span data-feather="layers"></span>
                  Contribution
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Profile Settings</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Update Profile
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Change password
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Create Privacy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </nav>

      
    {% else %}
<!-- <h1>You are not log in</h1> -->
    {% endif %}
  
    <div class="container">
    	
{% block main %}
{% endblock %}
    </div>

        

       

         
       
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

src/article/templates/blog_settings.html
{% extends "base.html" %}

{% block main %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Add Article </a>
<hr>
         {% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">History</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    You don't have an article yet ...

</div>
{% endif %}
  </main>

{% endblock %}

src/article/templates/blogs.html
{% extends "base.html" %}

{% block main %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div class="container">
  <div class="row">
    <div class="col-md-9">
      {% if articles %}
      {% for article in articles %}
       <h6 class="mt-4">{{article.title}}</h6>
        <p class="lead">
        {% if article.article_image %}
        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
        {% endif %}
        <p> Published by  {{article.author.username}} At  {{article.created_date}}</p>
        <hr>
        <p class="lead">
          {{article.content|safe|truncatewords:50}}
        </p>
        <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read more</a>
      <hr>
      {% endfor %}
    </div>
     <div class="col-md-3">
      <div class="row">
       <!--  <div class="col-md-4 order-md-2 mb-4"> -->
          <h6 class="d-flex justify-content-between align-items-center mb-2">
            <span class="text-muted"><strong> Your Can Read Also..</strong></span>
           
          </h6>
          <ul class="list-group mb-4">
            {% if articles %}
             {% for article in articles %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h5 >{{ article.title }}</h5>
                <small class="text-muted">
                   {{article.content|safe|truncatewords:20}}
                </small>
                 <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Read more</a>
              </div>
             <!--  <span class="text-muted">$12</span> -->
            </li>
            {% endfor %}
            {% else %}
                 <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">No blogs Exist</h6>
               
              </div>
            <!--   <span class="text-muted">$12</span> -->
            </li>

            {% endif %}
           
          </ul>
        </div>
     </div>
      </div>
      




{% else %}
<div class ="row">
  <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
      <div class = "alert alert-danger">No Articles Found</div>
      </div>
    </div>
</div>
</main>
{% endif %}
{% endblock %}

src/article/templates/chat_with_friend.html
{% extends "base.html" %}

{% block main %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
   
   <h1>May Be Later</h1>      
          
  </main>
{% endblock %}

src/article/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Control Board</h3>
<hr>
<p>
    Welcome, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Add Article </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">History</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    You don't have an article yet ...

</div>
{% endif %}



{% endblock body %}

src/article/templates/find_people.html
{% extends "base.html" %}

{% block main %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              
              <tbody>
               
                {% for i in users_list %}
                <tr>
                  <td>{{ i.username }}</td>
                  <td><a href="{{ i.repo_url }}" target="_blank">Add Friend</a></td>
                 
                </tr>
                {% endfor %}
              
               
              </tbody>
            </table>
          </div>
          
  </main>
{% endblock %}

src/article/templates/gallary.html
{% extends "base.html" %}

{% block main %}
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
   
   <h1>May Be Later (Gallary)</h1>      
          
  </main>
{% endblock %}

src/article/templates/git_hub.html
{% extends "base.html" %}

{% block main %}



  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
   <form class="form-signin" method="post">
      {% csrf_token %}
     
     
      <input type="text" id="inputEmail" name="repo_name" class="form-control" placeholder="Project Name" required autofocus>
     <br/>
      <input type="text" id="inputEmail" name="repo_url" class="form-control" placeholder="Project Url:" required autofocus>
      <br/>
      <textarea  type="text" id="inputEmail" name="repo_dec" class="form-control" placeholder="Project Description:" required autofocus></textarea>
       <br/>
      
      <button class="btn btn-primary" type="submit">Create Project</button>
    
    </form>
  </main>

{% endblock main %}

src/article/templates/login.html
{% extends "base.html" %}
{% block main %}
{% load crispy_forms_tags %}
 <main role="main" class="col-md-9 ml-sm-auto col-lg-11 pt-3 px-4">
     <div class="row">
        <div class="col-md-6 offset-md-3">
    
        <form method = "post">
            <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" style="margin-left: 180px;" alt="" width="72" height="72">
      <h1 style="margin-left: 140px;" class="h3 mb-3 font-weight-normal">Please sign in</h1>
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>  <a href="{% url 'user:register'  %}" style="margin-left: 150px;" class = "btn btn-danger">Create Account</a>
        </form>
    </div>
  </div>
 </main>


{% endblock main %}

src/article/templates/register.html
{% extends "base.html" %}

{% block main %}

{% load crispy_forms_tags %}

<main role="main" class="col-md-9 ml-sm-auto col-lg-11 pt-3 px-4">
     <div class="row">
        <div class="col-md-6 offset-md-3">
        <form method = "post">
             <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" style="margin-left: 180px;" alt="" width="72" height="72">
      <h1 style="margin-left: 140px;" class="h3 mb-3 font-weight-normal">Create Account</h1>
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
    <button type = "submit" class = "btn btn-danger">Create Account</button>  <a href="{% url 'user:login'  %}" style="margin-left: 150px;" class = "btn btn-danger">if you have account</a>
        </form>
    </div>
  </div>
 </main>

{% endblock main %}